- hosts:  webserver
  name: filtering the changes
  tasks:
    - name: allowing password based authentication
      lineinfile: 
        path: /etc/ssh/sshd_config  
        regexp: "^PasswordAuthentication no"
        line: "PasswordAuthentication yes"
        state:  present
